server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
#    resolve-schema-properties: true
#  writer-with-default-pretty-printer: true
#  override-with-generic-response: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    #org.springframework.boot.web.embedded.netty.NettyWebServer: WARN
    com.xxxxxx: DEBUG
    com.lergo.framework.filter.LogFilter: TRACE
    com.lergo.framework.filter.ResultFilter: DEBUG
############################################## 以上为调试配置，生产环境请删除 ##############################################
lergo:
  boot:
    with-jdbc: true
    with-redis: true
  filter:
    #authJWT: true
    authRedis: true
    auth-expire-seconds: 3600
    auth-header-name: token
    timer: true
    result: true

spring:
  application:
    name: @application.name@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@
  datasource:
    url: jdbc:postgresql://localhost/postgres?tringtype=unspecified
    username: postgres
    password: postgres
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  webflux.base-path: /api
mybatis-plus:
  configuration.default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

resilience4j:
  ratelimiter:
    instances:
      xxxxRateLimiter:
        limitForPeriod: 1 # 每秒允许的请求数量
        limitRefreshPeriod: 3000ms # 刷新周期
        timeoutDuration: 0ms # 超时时间