#server:
#  port: 8080

##############################################

application:
  artifactId: @application.artifactId@
  version: @application.version@
spring:
  application:
    name: @application.name@
  datasource:
    url: jdbc:postgresql://localhost/postgres?tringtype=unspecified
    username: postgres
    password: postgres

lergo:
  boot:
    with-jdbc: true
    with-redis: true
token:
  filter-flag: true
  header-name: token
