#server:
#  port: 8080

############################################## 以上为调试配置，生产环境请删除 ##############################################
lergo:
  boot:
    with-jdbc: true
    with-redis: true
  filter:
    auth: true
    auth-header-name: token
    timer: true
    result: true

spring:
  application:
    name: @application.name@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@
  datasource:
    url: jdbc:postgresql://localhost/postgres?tringtype=unspecified
    username: postgres
    password: postgres
