server:
  port: 8080

springdoc:
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.xxxxxx: debug
############################################## 以上为调试配置，生产环境请删除 ##############################################

application:
  artifactId: @application.artifactId@
  version: @application.version@

lergo:
  boot-with-jdbc: true
  #boot-with-redis: true

spring:
  application:
    name: @application.name@
  datasource:
    url: jdbc:postgresql://localhost/postgres?tringtype=unspecified
    username: postgres
    password: postgres
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  webflux.base-path: /api
mybatis-plus:
  configuration.default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

token:
  filter-flag: true
  header-name: token
